### ISSUE TITLE
rubocop.yml settings are ignored

### ISSUE THREAD

**Issue by CharlieIGG** [Shopify/ruby-lsp#1677]
### Operating System

MacOS 14.1.1 (23B81)

### Ruby version

ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]

### Project has a bundle

- [X] Has bundle

### Ruby version manager being used

rbenv

### Description

Hello Ruby LSP Team!

I'm extremely thankful for the amazing job you've done with this gem and the vscode extension.

I do have an issue I haven't been able to figure out: if I create a local rubocop.yml file, the settings I enter seem to be ignored. For example, disabling the following rule does nothing, I still get warnings whenever I use a service object pattern:

```yml
Lint/MissingSuper:
  Description: >-
    Checks for the presence of constructors and lifecycle callbacks
    without calls to `super`.
  Enabled: false
```

How can I get my rubocop settings to be acknowledged by the linter/formatter?
