### ISSUE TITLE
Pass environment variable to RuboCop

### ISSUE THREAD

**Issue by Earlopain** [Shopify/ruby-lsp#1679]
### This feature is VS Code specific

- [X] VS Code specific

### Use case

I have a project with a pretty large `.rubocop_todo.yml`. The rubocop config looks like this:
```yml
<% unless ENV["IGNORE_RUBOCOP_TODO"] %>
inherit_from: .rubocop_todo.yml
<% end %>

AllCops:
  NewCops: enable

# Other cop configuration ...
```

RuboCop interprets this ERB and depending on the ENV decides if it should load the todo. The reason for this is that I want to have all offenses highlighted in my editor, and CI and local rubocop runs should ignore these so that I don't get thousands of offenses.

### Description

I'd like a way to pass environment variables to rubocop/the language server, through something like `rubyLsp.environment` in order to make this work.

Edit: That might actually be more complicated that what is actually needed. A env var to signal running inside the lsp server would sufice. Similarly how github sets `CI=1` this could set `RUBY_LSP=1`. In that case, this issue should probably transferred to the server repo.
