### ISSUE TITLE
VSCode extension does not respect Rubocop ignored files

### ISSUE THREAD

**Issue by devonpmack** [Shopify/ruby-lsp#170]
## Expected

When opening a file that's ignored in `.rubocop.yml` 

eg. 

```yml
AllCops:
  Exclude:
    - ignored.rb
```

It should hide the errors

## Actual

It runs Rubocop on that file, and displays any errors it finds.

DM me on Slack for an example repo to reproduce on :)
