### ISSUE TITLE
Got error when running on Windows 11 WSL in docker container

### ISSUE THREAD

**Issue by mik356ua** [Shopify/ruby-lsp#1784]
### Ruby version

3.1.3

### Description

I use Windows 11 with WSL version 2 enabled and Ubuntu 22.04 distro installed. Also Docker Desktop installed to enable docker support. My ruby app source code located at Ubuntu filesystem and runs in docker container. When I install and enable Ruby LSP extension on 'WSL: Ubuntu' in vscode I see this error:
```
Failed to activate none environment: Command failed: /bin/bash -ic 'ruby -rjson -e "printf(%{RUBY_ENV_ACTIVATE%sRUBY_ENV_ACTIVATE}, JSON.dump(ENV.to_h))"' bash: initialize_job_control: no job control in background: Bad file descriptor your 131072x1 screen size is bogus. expect trouble your 131072x1 screen size is bogus. expect trouble Command 'ruby' not found, but can be installed with: sudo apt install ruby
```
Also I tried to add `gem "ruby-lsp"` to my `Gemfile` run `docker compose exec web bundle` and restart vscode but that didn't help (same error).

Here is my `Dockerfile`:
```
FROM ruby:3.1.3
RUN gem update --system && gem install bundler
RUN mkdir -p /app
WORKDIR /app
COPY Gemfile Gemfile.lock ./ 
RUN bundle install --jobs 20
EXPOSE 3000
CMD rm -f tmp/pids/server.pid && /app/bin/rails server -p 3000 -b '0.0.0.0';
```
and `docker-compose.yml`:
```
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: web
    stdin_open: true
    tty: true
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
```
Any help is much appreciated. Thanks in advance!

### Expected output

Expect ruby-lsp to start without any errors
